name: Build

on:
  push:
    branches:
      - master  # Altere para a branch principal do seu projeto (pode ser "master" também)
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Altere para a versão do Node.js que você está usando

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

        - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
